alias fsi="fsharpi"
alias fsc="fsharpc"
alias activate="source .env/bin/activate"
alias rm="echo STOP"
alias rmdir="echo STOP"
alias del="rmtrash"
alias work="cd ~/workspace"
alias work_dynet="cd ~/workspace/sequence-labelling/code/dynet;~/Desktop/test.sh"
alias pipll="pip list --format=columns"

