alias fsi="fsharpi"
alias fsc="fsharpc"
alias activate="source .env/bin/activate"
alias rm="echo STOP"
alias rmdir="echo STOP"
alias del="rmtrash"
alias work="cd ~/Workspace"
alias work_dynet="cd ~/Workspace/LearningML/dynet"
alias pipll="pip list --format=columns"
